
name = "taobao-mall-569906"
main = "worker.js"
compatibility_date = "2025-12-23"
workers_dev = true

[vars]
API_VERSION = "1.0.0"
ENVIRONMENT = "production"
DEPLOY_TIME = "2026-03-02T12:30:07.812Z"

[build]
command = "echo 'Building for Cloudflare...'"

[build.upload]
format = "service-worker"
